development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "0813167268ff50b415fa86a09fe80db30420f23ab27dea3e8f7c0b0f41722530"
  signature_expiration: 3600 # one hour
